<?php
namespace app\ftapi\controller;

use app\ftapi\model\Evaluate;
use think\Request;

class Evaluates extends Base
{

    public function get_list(Request $request)
    {
        $input = input();

        $where = [];
        if (!empty($input['result_time'])){
            if ($input['result_time'] > 0){
                $where = 'result_time > 0';
            }
            unset($input['result_time']);
        }

        $mEvaluate = new Evaluate();
        $rs = $mEvaluate->where($where)->getSearchResult($input);

        foreach ($rs['list'] as $k => $v){
            if ($v['cu_id'] > 0){
                $rs['list'][$k]['name'] = get_customer_name($v['cu_id']);
            }
            if ($v['sid'] > 0){
                $rs['list'][$k]['name'] = get_student_name($v['sid']);
            }
        }

        return $this->sendSuccess($rs);
    }

    public function get_detail(Request $request, $id = 0)
    {
        $eva_id = input('id/d');

        $mEvaluate = new Evaluate();
        $rs = $mEvaluate->get($eva_id);
        if ($rs['cu_id'] > 0){
            $rs['name'] = get_customer_name($rs['cu_id']);
        }
        if ($rs['sid'] > 0){
            $rs['name'] = get_student_name($rs['sid']);
        }

        return $this->sendSuccess($rs);
    }

    public function post(Request $request)
    {
        $post = $request->post();

        $mEvaluate = new Evaluate();
        $rs = $mEvaluate->createEvaluate($post);
        if ($rs === false) return $this->sendError(400,'Evaluate');

        return $this->sendSuccess();
    }

    public function put(Request $request, $id=0)
    {
        $eva_id = input('id/d');

        $mEvaluate = Evaluate::get($eva_id);
        if (!$mEvaluate) return $this->sendError(400,'评估不存在');

        $result = [
            'result' => input('result'),
            'result_time' => int_day(time()),
            ];
        $rs = $mEvaluate->addResult($eva_id,$result);
        if ($rs === false) return $this->sendError(400,'Evaluate');

        return $this->sendSuccess();
    }

    public function delete(Request $request, $id=0)
    {
        return parent::delete($request); // TODO: Change the autogenerated stub
    }


}