<?php
namespace app\api\controller;

use app\api\model\Evaluate;
use think\Request;

class Evaluates extends Base
{

    public function get_list(Request $request)
    {
        $input = input();

        $mEvaluate = new Evaluate();
        $rs = $mEvaluate->getSearchResult($input);

        return $this->sendSuccess($rs);
    }

    public function get_detail(Request $request, $id = 0)
    {
        $eva_id = input('id/d');

        $mEvaluate = new Evaluate();
        $rs = $mEvaluate->get($eva_id);
        return $this->sendSuccess($rs);
    }

    public function post(Request $request)
    {
        $post = $request->post();

        $mEvaluate = new Evaluate();
        $rs = $mEvaluate->createEvaluate($post);
        if ($rs === false) return $this->sendError(400,'Evaluate');

        return $this->sendSuccess();
    }

    public function put(Request $request, $id=0)
    {
        return parent::put($request); // TODO: Change the autogenerated stub
    }

    public function delete(Request $request, $id=0)
    {
        return parent::delete($request); // TODO: Change the autogenerated stub
    }


}