<?php
/**
 * 方法对应的翻译，用于操作行为记录
 */

return [
    //资源模块名  => '含义解释'
    'post:api/open/signin'                    => '用户登录操作：用户名:{account}',
    'post:api/sms_history'                    => '增加短信记录',
    'post:api/system/reset'                   => '系统重置',
    'post:api/open/vcode'                     => '发送验证码',
    'post:api/customers/do_reg'               => '客户转为学员',
    'put:api/dictionary/restful'              => '修改字典数据',
    'put:api/customer_follow_up/restful'      => '修改客户跟进记录',
    'delete:api/customer_follow_up/restful'   => '删除客户跟进记录',
    'delete:api/customer_follow_up'           => '删除客户跟进记录',
    'post:api/customers/restful_sub'          => '添加客户相关数据',
    'put:api/lessons/restful'                 => '修改课程',
    'post:api/orders/do_transfer'             => '订单结转',
    'post:api/course_arranges/delete_batch'   => '批量删除排课',
    'put:api/time_sections/restful'           => '修改上课时间段',
    'post:api/time_sections'                  => '添加上课时间段',
    'post:api/students'                       => '添加学员',
    'post:api/configs'                        => '添加系统配置',
    'put:api/configs/restful'                 => '修改系统配置',
    'put:api/classes/restful'                 => '修改班级',
    'post:api/classes'                        => '添加班级',
    'post:api/user/bind'                      => '绑定帐号',
    'post:api/index/sendCode'                 => '发送验证码',
    'post:api/course_arranges/restful_sub'    => '添加排课',
    'put:api/customers/restful'               => '修改客户',
    'post:sapi/users/switch_sid'              => '家长端切换默认学员',
    'post:api/subjects'                       => '添加科目',
    'post:api/review_tpl_defines'             => '课程绑定课评模板',
    'post:api/review_tpl_settings'            => '添加课评模板',
    'post:api/student_lessons/restful_sub'    => '学生购买课程',
    'put:api/employees/restful'               => '修改员工',
    'post:api/lessons'                        => '添加课程',
    'post:api/customers'                      => '添加客户',
    'delete:api/students/restful'             => '删除学员相关数据',
    'put:api/course_arranges/restful'         => '修改排课',
    'delete:api/course_arranges/restful'      => '删除排课',
    'delete:api/course_arranges'              => '删除排课',
    'post:api/classes/restful_sub'            => '添加班级',
    'post:api/homework_tasks'                 => '添加作业',
    'put:api/users/restful'                   => '修改帐户',
    'post:api/trial_listen_arrange'           => '添加试听',
    'post:api/orders/do_submit'               => '提交订单',
    'delete:api/orders/restful'               => '删除订单',
    'post:api/orders'                         => '添加订单',
    'post:api/orders/do_refund'               => '退款',
    'post:sapi/homework_tasks/restful_sub'    => '添加作业',
    'post:sapi/open/signin'                   => '学生端登录',
    'post:api/homework_completes/restful_sub' => '处理学生作业',
    'put:api/students/restful'                => '修改学员相关数据',
    'put:api/roles/restful'                   => '修改角色权限',
    'post:api/upload/restful'                 => '上传文件',
    'post:api/course_arranges'                => '添加排课',
    'post:api/orgs/restful_sub'               => '添加加盟商',
    'delete:api/subjects/restful'             => '删除科目',
    'delete:api/trial_listen_arrange/restful' => '删除试听',
    'delete:api/class_attendances/restful'    => '删除考勤',
    'put:api/backlogs/restful'                => '修改备忘',
    'post:api/broadcasts'                     => '添加广播',
    'post:api/backlogs'                       => '添加备忘',
    'delete:api/classrooms/restful'           => '删除教室',
    'post:sapi/share/employee'                => '分享员工',
    'post:api/holidays'                       => '添加节假日',
    'post:api/class_schedules'                => '班级添加排班',
    'post:api/tally_helps'                    => '添加记帐辅助核算',
    'post:api/tally_types'                    => '添加记帐类别',
    'post:sapi/advices'                       => '学员反馈意见',
    'delete:api/classes/restful'              => '删除班级',
    'post:api/order_items/do_assign'          => '订单分班',
    'post:api/roles/restful_sub'              => '添加角色相关',
    'post:api/classes/do_transfer'            => '班级转班',
    'post:api/students/restful_sub'           => '添加学员相关',
    'post:api/employee_dimissions'            => '员工辞职',
    'post:sapi/student_leaves'                => '学员请假',
    'post:api/season_dates'                   => '添加季度日期',
    'delete:api/departments/restful'          => '删除部门',
    'delete:api/time_sections/restful'        => '删除排课时间',
    'post:api/index/unlock'                   => '解锁',
    'put:api/index/profile'                   => '修改资料',
    'post:api/student_attendances/free'       => '自由考勤',
    'post:api/orders/restful_sub'             => '报名缴费',
    'post:api/orders/do_supplement'           => '补缴',
    'delete:api/classes/restful_sub'          => '删除班级',
    'delete:api/customers/restful'            => '删除客户',
    'put:api/handover_moneys/restful'         => '修改交班记录',
    'post:api/tallys'                         => '记帐',
    'post:api/handover_moneys'                => '交班交款',
    'post:api/handover_works'                 => '交班',
    'post:api/course_arranges/remind_course'  => '排课提醒',
    'post:api/reviews'                        => '点评',
    'post:sapi/users/edit_profile'            => '家长修改帐号',
    'post:api/report_summaries'               => '刷新运营统计',
    'post:api/public_schools'                 => '添加公立学校',
    'post:api/materials/restful_sub'          => '添加物品相关',
    'post:api/materials'                      => '添加物品',
    'post:api/time_sections/restful_sub'      => '添加上课时间段',
    'put:api/classrooms/restful'              => '修改教室',
    'post:api/classrooms'                     => '添加教室',
    'delete:api/employees/restful'            => '删除员工',
    'post:api/employees'                      => '添加员工',
    'post:api/employees/restful_sub'          => '添加员工相关',
    'put:api/branches/restful'                => '修改校区相关',
    'put:api/departments/restful'             => '相关部门相关数据',
    'post:api/departments'                    => '添加部门',
    'post:api/accounting_accounts'            => '添加收入帐户',
    'post:wxopen/message/index'               => '微信消息通知',
    'post:api/wxmp_menus'                     => '添加微信菜单',
    'post:api/wxmp_templates/sync'            => '同步微信消息模板',
    'put:api/configs/edit_center_params'      => '修改配置',
    'post:api/roles'                          => '添加角色',
    'post:api/dictionary'                     => '添加字典',
    




];
