<?php
return [
    'messag_push' => '{
     "title": "收到一条新的考勤通知!",
     "context": "新的考勤通知！学员姓名：圆圆,时间：2018-04-21 10:15,地点：香瑞园校区!",
     "sid": 15,
     "message_type": 2,
     "relation_id": 36
}',
    'user_signup' => '{
               "uid": 10010,
               "og_id": 0,
               "account": "13590400035",
               "mobile": "13590400035",
               "email": "",
               "name": "李三",
               "sex": "1",
               "user_type": 2,
               "salt": "pjL86w",
               "password": "8cf98831c80f0561fc64598688d9cbf8",
               "avatar": "",
               "openid": "",
               "default_sid": 4,
               "is_mobile_bind": 0,
               "is_email_bind": 0,
               "is_weixin_bind": 0,
               "last_login_time": 0,
               "last_login_ip": "",
               "login_times": 0,
               "create_time": "2018-04-18 17:22:34",
               "status": 1,
               "is_main": 0,
               "is_admin": 0,
               "update_time": 1525921526,
               "create_uid": 10001,
               "is_delete": 0,
               "delete_time": null,
               "delete_uid": 0,
               "reset_time": null,
               "reset_token": null,
               "sid": 4,
               "bid": 2,
               "student_name": "廖一Yi",
               "pinyin": "",
               "pinyin_abbr": "",
               "nick_name": "Yi",
               "photo_url": "http://s10.xiao360.com/qms/student_avatar/10001/18/04/27/defee772b5c45393098c5581201f2f56.jpeg",
               "birth_time": 0,
               "birth_year": 0,
               "birth_month": 0,
               "birth_day": 0,
               "school_grade": 0,
               "school_class": "0",
               "school_id": 1,
               "first_tel": "13530200068",
               "first_family_name": "廖志强",
               "first_family_rel": 4,
               "first_uid": 10009,
               "second_family_name": "香瑞园",
               "second_family_rel": 0,
               "second_tel": "",
               "second_uid": 0,
               "eid": 0,
               "sno": "",
               "card_no": "",
               "money": "0.00",
               "credit": "0.00",
               "credit2": "0.00",
               "vip_level": 0,
               "last_attendance_time": "2018-05-05 10:15:00",
               "is_lost": 0,
               "quit_reason": "",
               "student_type": 1,
               "option_fields": [],
               "student_lesson_times": 64,
               "student_lesson_remain_times": 35,
               "student_lesson_hours": "64.00",
               "student_lesson_remain_hours": "34.00",
               "ext_id": "",
               "first_openid": "",
               "second_openid": ""
}'
];